# Generated by Django 3.0.5 on 2020-04-18 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user/avatar', verbose_name='Аватар')),
                ('firstname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Рост')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Вес')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('sex', models.CharField(max_length=15, verbose_name='Пол')),
                ('isSmoking', models.CharField(max_length=5, verbose_name='Курение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
