# Generated by Django 3.0.5 on 2020-04-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.PositiveSmallIntegerField(default='0', verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(blank=True, default='Имя', max_length=40, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='height',
            field=models.PositiveSmallIntegerField(default='0', verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='isSmoking',
            field=models.CharField(default='нет', max_length=5, verbose_name='Курение'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(blank=True, default='Фамилия', max_length=40, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(default='муж', max_length=15, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='weight',
            field=models.PositiveSmallIntegerField(default='0', verbose_name='Вес'),
        ),
    ]
