# Generated by Django 3.0.5 on 2020-04-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200419_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, default='user/avatar/default.jpg', null=True, upload_to='user/avatar', verbose_name='Аватар'),
        ),
    ]
