# Generated by Django 3.0.3 on 2020-05-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200419_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dias_pressure',
            field=models.PositiveSmallIntegerField(default='0', null=True, verbose_name='Текущее диастолическое давление'),
        ),
        migrations.AddField(
            model_name='employee',
            name='measurements_count',
            field=models.PositiveSmallIntegerField(default='0', verbose_name='Количество анализов'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pulse',
            field=models.PositiveSmallIntegerField(default='0', null=True, verbose_name='Текущий пульс'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sys_pressure',
            field=models.PositiveSmallIntegerField(default='0', null=True, verbose_name='Текущее систолическое давление'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/users/default.jpg', null=True, upload_to='static/images/users/', verbose_name='Аватар'),
        ),
    ]
