# Generated by Django 3.0.3 on 2020-05-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200514_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='measurements_count',
        ),
    ]
